#!/usr/bin/env sh
if ! mypy .;
then
    echo "Commit rejected. Fix mypy errors." >&2
    exit 1
fi

SRC_FILE_LIST=$(git diff --cached --name-only --diff-filter=AMR | grep '.*\.py')
if [ -n "$SRC_FILE_LIST" ]
then
    if ! flake8 "$SRC_FILE_LIST";
    then
        echo "Commit rejected. Fix flake8 errors." >&2
        exit 1
    fi
fi
