# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
	# git
	add-apt-repository ppa:git-core/ppa
	apt update
	apt install git -y

	# pyenv
	curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
	echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc 
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
	. .bashrc
  SHELL
end
